# Generated by Django 5.0 on 2026-03-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='budget_currency',
            new_name='budget_amount',
        ),
    ]
