# Generated by Django 5.0 on 2026-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('deliverable', 'Deliverable'), ('reference', 'Reference'), ('brand_guideline', 'Brand Guideline')], max_length=20),
        ),
    ]
