# Generated by Django 5.0 on 2026-02-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['project', 'category', 'status'], name='feedback_fe_project_81aee5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submitted_at'], name='feedback_fe_submitt_c84e00_idx'),
        ),
    ]
