# Generated by Django 5.0 on 2026-03-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client',
        ),
    ]
