# Generated by Django 5.0 on 2026-03-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_messages', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='content_text',
        ),
    ]
